import 'package:online_learning_huweii/src/models/hotel_model.dart';

List<HotelModel> listHotels = <HotelModel>[
  HotelModel(
      id: '1232434',
      isFavorite: false,
      name: 'Do dolore pariatur proident ',
      featureImage: 'assets/images/image_feature/feature_image.jpeg',
      location: 'Moll de Barcelona WTC, 08039 Barcelona',
      starRate: 3,
      numberReviewers: 12,
      pricePerNight: 324,
      listPictures: [
        'assets/images/list_image_hotel/1.jpeg',
        'assets/images/list_image_hotel/2.jpeg',
        'assets/images/list_image_hotel/3.jpeg',
        'assets/images/list_image_hotel/4.jpeg',
        'assets/images/list_image_hotel/5.jpeg',
        'assets/images/list_image_hotel/6.jpeg',
        'assets/images/list_image_hotel/7.jpeg',
      ],
      description:
          'Consectetur officia irure pariatur esse non qui. Dolor quis in ipsum elit. Velit nulla id nostrud anim.'),
  HotelModel(
      id: '287364928',
      isFavorite: false,
      name: 'Voluptate velit ipsum  ',
      featureImage: 'assets/images/image_feature/feature_image.jpeg',
      location: 'Moll de Barcelona WTC, 08039 Barcelona',
      starRate: 4,
      numberReviewers: 17,
      pricePerNight: 194,
      listPictures: [
        'assets/images/list_image_hotel/1.jpeg',
        'assets/images/list_image_hotel/2.jpeg',
        'assets/images/list_image_hotel/4.jpeg',
        'assets/images/list_image_hotel/3.jpeg',
        'assets/images/list_image_hotel/6.jpeg',
        'assets/images/list_image_hotel/5.jpeg',
        'assets/images/list_image_hotel/7.jpeg',
      ],
      description:
          'Tempor sint exercitation reprehenderit ad eiusmod et quis ut consequat. Ullamco proident aliquip quis tempor eiusmod esse duis adipisicing sit aliquip dolore cillum. Anim nisi fugiat magna ut. Nisi aute ex do tempor ea velit culpa laborum pariatur esse commodo.'),
  HotelModel(
      id: '8238472343',
      isFavorite: false,
      name: 'Laboris esse est aliqua ',
      featureImage: 'assets/images/image_feature/feature_image.jpeg',
      location: 'Barcelona/Spain',
      starRate: 5,
      numberReviewers: 5,
      pricePerNight: 332,
      listPictures: [
        'assets/images/list_image_hotel/1.jpeg',
        'assets/images/list_image_hotel/4.jpeg',
        'assets/images/list_image_hotel/2.jpeg',
        'assets/images/list_image_hotel/3.jpeg',
        'assets/images/list_image_hotel/5.jpeg',
        'assets/images/list_image_hotel/6.jpeg',
        'assets/images/list_image_hotel/7.jpeg',
      ],
      description:
          'Nulla fugiat Lorem eiusmod do quis. Irure sint deserunt mollit Lorem ut laboris est anim minim consectetur tempor qui non proident. Veniam nostrud nulla culpa ea. Aute anim deserunt ut proident consectetur mollit tempor laboris adipisicing ea labore sint officia velit..'),
  HotelModel(
      id: '34589372',
      isFavorite: false,
      name: 'Dolore eu labore  ',
      featureImage: 'assets/images/image_feature/feature_image.jpeg',
      location: 'Barcelona/Spain',
      starRate: 2,
      numberReviewers: 14,
      pricePerNight: 201,
      listPictures: [
        'assets/images/list_image_hotel/1.jpeg',
        'assets/images/list_image_hotel/3.jpeg',
        'assets/images/list_image_hotel/2.jpeg',
        'assets/images/list_image_hotel/4.jpeg',
        'assets/images/list_image_hotel/6.jpeg',
        'assets/images/list_image_hotel/5.jpeg',
        'assets/images/list_image_hotel/7.jpeg',
      ],
      description:
          'Est in ex ullamco amet cillum officia mollit labore et dolore. Aliqua exercitation aliquip ad elit commodo ut ea non pariatur. Non fugiat sunt ad ex ipsum pariatur occaecat. Quis enim eiusmod elit fugiat. Sit in duis enim consequat magna ut..'),
  HotelModel(
      id: '394857298',
      isFavorite: true,
      name: 'Proident aliqua reprehenderit  ',
      featureImage: 'assets/images/image_feature/feature_image.jpeg',
      location: 'Barcelona/Spain',
      starRate: 3,
      numberReviewers: 12,
      pricePerNight: 324,
      listPictures: [
        'assets/images/list_image_hotel/1.jpeg',
        'assets/images/list_image_hotel/3.jpeg',
        'assets/images/list_image_hotel/2.jpeg',
        'assets/images/list_image_hotel/4.jpeg',
        'assets/images/list_image_hotel/6.jpeg',
        'assets/images/list_image_hotel/5.jpeg',
        'assets/images/list_image_hotel/7.jpeg',
      ],
      description:
          'Dolor sunt eu laborum mollit culpa quis ut. Non aliquip et pariatur ipsum. Fugiat ad eu mollit aliquip veniam ut id fugiat cillum. Dolor laboris aliqua eiusmod eiusmod quis quis amet culpa. Tempor ex anim qui mollit irure aliqua enim sint in mollit..'),
];
